(function(g){var window=this;'use strict';var Igb=function(a,b){a.Pa("onAutonavCoundownStarted",b)},a6=function(a,b,c){g.bq(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.zg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.pM&&(b.lengthText?(e=b.lengthText||null,f=b.yv||null):b.lengthSeconds&&(e=g.dR(b.lengthSeconds),f=g.dR(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.nM(d).type;var l=b instanceof g.pM?b.isLivePlayback:null,m=b instanceof g.pM?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,t=[],u=[];n&&t.push(n);p&&(t.push(p),u.push(p));q&&u.push(q);c={title:b.title,author:n,author_and_views:t.join(" \u2022 "),aria_label:b.ariaLabel||
g.XO("Regarder $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Ck(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:u.join(" \u2022 "),autoplayAlternativeHeader:b.Or};b instanceof g.oM&&(c.playlist_length=b.playlistLength);a.update(c)},b6=function(a){var b=a.W(),c=b.C;
g.V.call(this,{I:"a",S:"ytp-autonav-suggestion-card",Y:{href:"{{url}}",target:c?b.ea:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},X:[{I:"div",Ka:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Y:{style:"{{background}}"},X:[{I:"div",Y:{"aria-label":"{{timestamp}}"},Ka:["ytp-autonav-timestamp"],xa:"{{duration}}"},{I:"div",Ka:["ytp-autonav-live-stamp"],xa:"En direct"},
{I:"div",Ka:["ytp-autonav-upcoming-stamp"],xa:"\u00c0 venir"},{I:"div",S:"ytp-autonav-list-overlay",X:[{I:"div",S:"ytp-autonav-mix-text",xa:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ka:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],xa:"{{title}}"},{I:"div",Ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],xa:"{{author}}"},{I:"div",Ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],xa:"{{views_and_publish_time}}"}]});this.G=
a;this.suggestion=null;this.j=c;this.Sa("click",this.onClick);this.Sa("keypress",this.onKeyPress)},c6=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.J=b;this.D=void 0;this.B=0;this.container=new g.V({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.J(this,this.container);this.container.Ha(this.element);b=a.W();var d=b.C;this.G=a;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.V({I:"div",S:"ytp-autonav-endscreen-upnext-container",Y:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},X:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",xa:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",Y:{href:"{{url}}",target:d?b.ea:""},X:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",Y:{style:"{{background}}"},X:[{I:"div",Y:{"aria-label":"{{timestamp}}"},Ka:["ytp-autonav-timestamp"],
xa:"{{duration}}"},{I:"div",Ka:["ytp-autonav-live-stamp"],xa:"En direct"},{I:"div",Ka:["ytp-autonav-upcoming-stamp"],xa:"\u00c0 venir"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",X:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",xa:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",xa:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",xa:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",xa:"{{author_and_views}}"}]}]}]});
g.J(this,this.j);this.j.Ha(this.container.element);d||this.T(this.j.Fa("ytp-autonav-endscreen-link-container"),"click",this.CQ);this.G.tb(this.container.element,this,115127);this.G.tb(this.j.Fa("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({I:"div",S:"ytp-autonav-overlay"});g.J(this,this.overlay);this.overlay.Ha(this.container.element);this.u=new g.V({I:"div",S:"ytp-autonav-endscreen-button-container"});g.J(this,this.u);this.u.Ha(this.container.element);this.cancelButton=
new g.V({I:"button",Ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{"aria-label":"Annuler la lecture automatique"},xa:"Annuler"});g.J(this,this.cancelButton);this.cancelButton.Ha(this.u.element);this.cancelButton.Sa("click",this.QZ,this);this.G.tb(this.cancelButton.element,this,115129);this.playButton=new g.V({I:"a",Ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{href:"{{url}}",role:"button","aria-label":"Lire la vid\u00e9o suivante"},xa:"Regarder"});g.J(this,this.playButton);this.playButton.Ha(this.u.element);this.playButton.Sa("click",this.CQ,this);this.G.tb(this.playButton.element,this,115130);this.C=new g.Qp(function(){Jgb(c)},500);
g.J(this,this.C);this.BQ();this.T(a,"autonavvisibility",this.BQ);this.G.N("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.PZ),this.T(a,"onAutonavCoundownStarted",this.t5))},d6=function(a){var b=a.G.Bk(!0,a.G.isFullscreen());
g.bq(a.container.element,"ytp-autonav-endscreen-small-mode",a.ah(b));g.bq(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.bI);g.bq(a.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.G.Df());g.bq(a.G.getRootNode(),"countdown-running",a.Ik());g.bq(a.container.element,"ytp-player-content",a.G.Df());g.$m(a.overlay.element,{width:b.width+"px"});if(!a.Ik()){a.G.Df()?Kgb(a,Math.round(Lgb(a)/1E3)):Kgb(a);b=!!a.suggestion&&!!a.suggestion.Or;var c=a.G.Df()||!b;
g.bq(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.bq(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.wQ(a.u,a.G.Df());g.bq(a.element,"ytp-enable-w2w-color-transitions",Mgb(a))}},Jgb=function(a){var b=Lgb(a),c=Math,d=c.min;
var e=a.B?Date.now()-a.B:0;c=d.call(c,e,b);Kgb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Ik()?a.select(!0):a.Ik()&&a.C.start()},Lgb=function(a){if(a.G.isFullscreen()){var b;
a=null==(b=a.G.getVideoData())?void 0:b.gQ;return-1===a||void 0===a?8E3:a}return 0<=a.G.us()?a.G.us():g.PJ(a.G.W().experiments,"autoplay_time")||1E4},Mgb=function(a){var b;
return!(null==(b=a.G.getVideoData())||!b.watchToWatchTransitionRenderer)},Kgb=function(a,b){b=void 0===b?-1:b;
a=a.j.Fa("ytp-autonav-endscreen-upnext-header");g.af(a);if(0<=b){b=String(b);var c="Prochaine vid\u00e9o dans $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Prochaine vid\u00e9o dans $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Ze("Prochaine vid\u00e9o dans $SECONDS".slice(0,d)));var e=g.Ye("span");g.Wp(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.lf(e,b);a.appendChild(e);a.appendChild(g.Ze("Prochaine vid\u00e9o dans $SECONDS".slice(d+c.length)));return}}g.lf(a,"\u00c0 suivre")},
e6=function(a,b){g.V.call(this,{I:"div",
Ka:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},f6=function(a){g.V.call(this,{I:"div",
Ka:["ytp-upnext","ytp-player-content"],Y:{"aria-label":"{{aria_label}}"},X:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",Y:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",X:[{I:"span",S:"ytp-upnext-header",xa:"\u00c0 suivre"},{I:"span",S:"ytp-upnext-title",xa:"{{title}}"},{I:"span",S:"ytp-upnext-author",xa:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",Y:{role:"button",href:"{{url}}","aria-label":"Lire la vid\u00e9o suivante"},X:[{I:"svg",Y:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},X:[{I:"circle",S:"ytp-svg-autoplay-circle",Y:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",Y:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",Y:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",X:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
xa:"La lecture automatique est d\u00e9sactiv\u00e9e"}]}]});this.api=a;this.cancelButton=null;this.D=this.Fa("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.Qp(this.cF,5E3,this);this.u=0;var b=this.Fa("ytp-upnext-cancel");this.cancelButton=new g.V({I:"button",Ka:["ytp-upnext-cancel-button","ytp-button"],Y:{tabindex:"0","aria-label":"Annuler la lecture automatique"},xa:"Annuler"});g.J(this,this.cancelButton);this.cancelButton.Sa("click",this.RZ,this);this.cancelButton.Ha(b);
this.cancelButton&&this.api.tb(this.cancelButton.element,this,115129);g.J(this,this.C);this.api.tb(this.element,this,18788);b=this.Fa("ytp-upnext-autoplay-icon");this.T(b,"click",this.SZ);this.api.tb(b,this,115130);this.DQ();this.T(a,"autonavvisibility",this.DQ);this.T(a,"mdxnowautoplaying",this.g6);this.T(a,"mdxautoplaycanceled",this.h6);g.bq(this.element,"ytp-upnext-mobile",this.api.W().u)},Ngb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.gQ;return-1===a||void 0===a?8E3:a}return 0<=a.api.us()?a.api.us():g.PJ(a.api.W().experiments,"autoplay_time")||1E4},Ogb=function(a,b){b=Ngb(a,b);
var c=Math,d=c.min;var e=(0,g.gB)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Ik()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Ik()&&a.j.start()},g6=function(a){e6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.V({I:"div",S:"ytp-suggestion-panel",X:[{I:"div",Ka:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],xa:"Plus de vid\u00e9os"}]});this.K=new g.V({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.J=!1;this.u=new c6(this.player);g.J(this,this.u);this.u.Ha(this.element);a.getVideoData().Ie?this.j=this.u:(this.j=new f6(a),g.sS(this.player,this.j.element,4),g.J(this,this.j));this.overlay=new g.V({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.J(this,this.overlay);this.overlay.Ha(this.element);this.C=new g.lI(this);g.J(this,this.C);g.J(this,this.table);this.table.Ha(this.element);this.table.show();g.J(this,this.K);this.K.Ha(this.table.element);this.hide()},h6=function(a){var b=a.Df();
b!==a.D&&(a.D=b,a.player.oa("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},i6=function(a,b){g.V.call(this,{I:"button",
Ka:["ytp-watch-on-youtube-button","ytp-button"],xa:"{{content}}"});this.G=a;this.buttonType=this.buttonType=b;b=this.G.getVideoData();if(a.N("embeds_enable_server_driven_watch_again_on_youtube")){var c,d;if(c=(a=null==(c=b.kd)?void 0:null==(d=c.playerOverlays)?void 0:d.playerOverlayRenderer)&&g.Q(a.watchOnYoutubeButton,g.UJa))this.j=c}if(this.j)this.update({content:this.j.title}),this.G.Mf(this.element,this),this.G.Vf(this.element,this.j.trackingParams||null);else{switch(this.buttonType){case 1:c=
"Regarder \u00e0 nouveau sur YouTube";d=156915;break;case 2:c="Continuer \u00e0 regarder sur YouTube";d=156942;break;default:c="Continuer \u00e0 regarder sur YouTube",d=156942}this.update({content:c});this.G.tb(this.element,this,d)}2===this.buttonType&&g.Yp(this.element,"ytp-continue-watching-button");this.Sa("click",this.onClick);g.wQ(this,!0)},j6=function(a,b){e6.call(this,a,"embeds-lite-endscreen");
this.G=a;this.j=b;this.G.tb(this.element,this,156943);this.watchButton=new i6(a,2);g.J(this,this.watchButton);this.watchButton.Ha(this.element);this.hide()},Pgb=function(a){e6.call(this,a,"subscribecard-endscreen");
this.j=new g.V({I:"div",S:"ytp-subscribe-card",X:[{I:"img",S:"ytp-author-image",Y:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",X:[{I:"div",S:"ytp-author-name",xa:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.J(this,this.j);this.j.Ha(this.element);var b=a.getVideoData();this.subscribeButton=new g.dU("S'abonner",null,"Se d\u00e9sabonner",null,!0,!1,b.dk,b.subscribed,"trailer-endscreen",null,a);g.J(this,this.subscribeButton);this.subscribeButton.Ha(this.j.Fa("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ra);this.Ra();this.hide()},k6=function(a){var b=a.W(),c=g.oI||g.MK?{style:"will-change: opacity"}:void 0,d=b.C,e=["ytp-videowall-still"];
b.u&&e.push("ytp-videowall-show-text");g.V.call(this,{I:"a",Ka:e,Y:{href:"{{url}}",target:d?b.ea:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},X:[{I:"div",S:"ytp-videowall-still-image",Y:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",Y:{"aria-hidden":"true"},X:[{I:"span",S:"ytp-videowall-still-info-bg",X:[{I:"span",S:"ytp-videowall-still-info-content",Y:c,X:[{I:"span",S:"ytp-videowall-still-info-title",xa:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",xa:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",xa:"En direct"},{I:"span",S:"ytp-videowall-still-info-duration",xa:"{{duration}}"}]}]}]},{I:"span",Ka:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},X:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",X:[" (",{I:"span",xa:"{{playlist_length}}"},")"]}]},{I:"span",Ka:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},X:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",xa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.lI(this);g.J(this,this.j);this.Sa("click",this.onClick);this.Sa("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.Mf(this.element,this);this.onVideoDataChange()},l6=function(a){e6.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.K=!1;this.V=null;this.u=new g.lI(this);g.J(this,this.u);this.J=new g.Qp(function(){g.Yp(b.element,"ytp-show-tiles")},0);
g.J(this,this.J);var c=new g.V({I:"button",Ka:["ytp-button","ytp-endscreen-previous"],Y:{"aria-label":"Pr\u00e9c\u00e9dente"},X:[g.AQ()]});g.J(this,c);c.Ha(this.element);c.Sa("click",this.WZ,this);this.table=new g.tQ({I:"div",S:"ytp-endscreen-content"});g.J(this,this.table);this.table.Ha(this.element);c=new g.V({I:"button",Ka:["ytp-button","ytp-endscreen-next"],Y:{"aria-label":"Suivante"},X:[g.BQ()]});g.J(this,c);c.Ha(this.element);c.Sa("click",this.VZ,this);a.getVideoData().Ie?this.j=new c6(a,!0):
this.j=new f6(a);g.J(this,this.j);g.sS(this.player,this.j.element,4);a.tb(this.element,this,158789);this.hide()},m6=function(a){return g.tS(a.player)&&a.UA()&&!a.C},n6=function(a){var b=a.Df();
b!==a.K&&(a.K=b,a.player.oa("autonavvisibility"))},o6=function(a){e6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new i6(a,1);g.J(this,this.watchButton);this.watchButton.Ha(this.element);g.h8a(a)&&(this.j=new g.$2(a,g.cS(a)),g.J(this,this.j),this.u=new g.V({I:"div",Ka:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Y:{tabIndex:"-1"},X:[this.j]}),g.J(this,this.u),this.j.Ha(this.u.element),this.u.Ha(this.element));a.tb(this.element,this,156914);this.hide()},Tgb=function(a){g.uT.call(this,a);
var b=this;this.endScreen=null;this.u=this.j=this.B=this.C=!1;this.listeners=new g.lI(this);g.J(this,this.listeners);var c=a.W(),d=a.getVideoData();d=d&&0!==d.endSeconds;if(g.Mz(g.eL(c))&&d&&!g.pS(a))this.u=!0,this.endScreen=new j6(a,g.cS(a));else{var e;(c.N("shorts_mode_to_player_api")?a.Yb():null==(e=g.cS(a))?0:e.Yb())?this.endScreen=new o6(a):Qgb(a)?(this.C=!0,Rgb(this),this.j?this.endScreen=new g6(a):this.endScreen=new l6(a)):c.Rg?this.endScreen=new Pgb(a):this.endScreen=new e6(a)}g.J(this,this.endScreen);
g.sS(a,this.endScreen.element,4);Sgb(this);this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.uE("endscreen"),function(f){b.onCueRangeEnter(f)});
this.listeners.T(a,g.vE("endscreen"),function(f){b.onCueRangeExit(f)})},Rgb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.pm&&a.B===b.Ie)return!1;a.j=b.pm;a.B=b.Ie;return!0},Qgb=function(a){a=a.W();
return a.yd&&!a.Rg},Sgb=function(a){a.player.Ge("endscreen");
var b=a.player.getVideoData();b=new g.sE(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.sE(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Je([b,c])};
g.TV.prototype.Nz=g.ca(36,function(a){this.cO!==a&&(this.cO=a,this.ql())});
g.HU.prototype.Zq=g.ca(35,function(a){this.u!==a&&(this.u=a,this.Ra())});
g.TV.prototype.Zq=g.ca(34,function(a){this.shareButton&&this.shareButton.Zq(a)});
g.DU.prototype.Yq=g.ca(33,function(a){this.u!==a&&(this.u=a,this.Ra())});
g.TV.prototype.Yq=g.ca(32,function(a){this.overflowButton&&this.overflowButton.Yq(a)});
g.UT.prototype.LD=g.ca(31,function(a){this.dO!==a&&(this.dO=a,this.yp())});
g.lS.prototype.us=g.ca(5,function(){return this.app.us()});
g.yZ.prototype.us=g.ca(4,function(){return this.getVideoData().TR});g.x(b6,g.V);b6.prototype.select=function(){this.G.Nn(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.mB||void 0)&&this.G.rb(this.element)};
b6.prototype.onClick=function(a){g.IS(a,this.G,this.j,this.suggestion.sessionData||void 0)&&this.select()};
b6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.mP(a)||(this.select(),g.nP(a))}};g.x(c6,g.V);g.k=c6.prototype;g.k.uE=function(a){this.suggestion!==a&&(this.suggestion=a,a6(this.j,a),this.playButton.updateValue("url",this.suggestion.Ck()),d6(this))};
g.k.Ik=function(){return 0<this.B};
g.k.Vz=function(){this.Ik()||(this.B=Date.now(),Jgb(this),Igb(this.G,Lgb(this)),g.bq(this.G.getRootNode(),"countdown-running",this.Ik()))};
g.k.Nv=function(){this.rr();Jgb(this);var a=this.j.Fa("ytp-autonav-endscreen-upnext-header");a&&g.lf(a,"\u00c0 suivre")};
g.k.rr=function(){this.Ik()&&(this.C.stop(),this.B=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.rr()};
g.k.CQ=function(a){g.IS(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.rb(this.playButton.element):a.currentTarget===this.j.Fa("ytp-autonav-endscreen-link-container")&&(a=this.j.Fa("ytp-autonav-endscreen-link-container"),this.G.Xa(a,!0),this.G.rb(a)),this.select())};
g.k.QZ=function(){this.G.rb(this.cancelButton.element);g.nS(this.G,!0);this.D&&this.G.Pa("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.g1)?void 0:c.command};
g.k.t5=function(a){if(Mgb(this)){var b=this.G.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.kR(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.kR(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.kR(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.kR(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.kR(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.kR(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.bq(this.element,"ytp-w2w-animate",!0)}};
g.k.PZ=function(a){this.G.N("web_autonav_color_transition")&&2!==a&&g.bq(this.element,"ytp-w2w-animate",!1)};
g.k.BQ=function(){var a=this.G.Df();this.J&&this.Bb!==a&&g.wQ(this,a);d6(this);this.G.Xa(this.container.element,a);this.G.Xa(this.cancelButton.element,a);this.G.Xa(this.j.Fa("ytp-autonav-endscreen-link-container"),a);this.G.Xa(this.playButton.element,a)};
g.k.ah=function(a){return 400>a.width||459>a.height};g.x(e6,g.V);g.k=e6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.UA=function(){return!1};
g.k.Df=function(){return!1};
g.k.YU=function(){return!1};g.x(f6,g.V);g.k=f6.prototype;g.k.cF=function(){this.notification&&(this.C.stop(),this.Ic(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.uE=function(a){this.suggestion=a;a6(this,a,"hqdefault.jpg")};
g.k.DQ=function(){g.wQ(this,this.api.Df());this.api.Xa(this.element,this.api.Df());this.api.Xa(this.Fa("ytp-upnext-autoplay-icon"),this.api.Df());this.cancelButton&&this.api.Xa(this.cancelButton.element,this.api.Df())};
g.k.p6=function(){window.focus();this.cF()};
g.k.Vz=function(a){var b=this;this.Ik()||(g.LC("a11y-announce","\u00c0 suivre "+this.suggestion.title),this.u=(0,g.gB)(),this.j=new g.Qp(function(){Ogb(b,a)},25),Ogb(this,a),Igb(this.api,Ngb(this,a)));
g.$p(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Ik=function(){return!!this.j};
g.k.Nv=function(){this.rr();this.u=(0,g.gB)();Ogb(this);g.Yp(this.element,"ytp-upnext-autoplay-paused")};
g.k.rr=function(){this.Ik()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.W().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.cF(),this.notification=new Notification("\u00c0 suivre",{body:this.suggestion.title,icon:this.suggestion.zg()}),this.B=this.T(this.notification,"click",this.p6),this.C.start())}this.rr();this.api.nextVideo(!1,a)};
g.k.SZ=function(a){!g.kf(this.cancelButton.element,g.lP(a))&&g.IS(a,this.api)&&(this.api.Df()&&this.api.rb(this.Fa("ytp-upnext-autoplay-icon")),this.select())};
g.k.RZ=function(){this.api.Df()&&this.cancelButton&&this.api.rb(this.cancelButton.element);g.nS(this.api,!0)};
g.k.g6=function(a){this.api.getPresentingPlayerType();this.show();this.Vz(a)};
g.k.h6=function(){this.api.getPresentingPlayerType();this.rr();this.hide()};
g.k.ra=function(){this.rr();this.cF();g.V.prototype.ra.call(this)};g.x(g6,e6);g.k=g6.prototype;g.k.create=function(){e6.prototype.create.call(this);this.C.T(this.player,"appresize",this.yA);this.C.T(this.player,"onVideoAreaChange",this.yA);this.C.T(this.player,"videodatachange",this.onVideoDataChange);this.C.T(this.player,"autonavchange",this.EQ);this.C.T(this.player,"autonavcancel",this.TZ);this.onVideoDataChange()};
g.k.show=function(){e6.prototype.show.call(this);(this.J||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.nS(this.player,!1);g.tS(this.player)&&this.UA()&&!this.B?(h6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.Vz():3===this.videoData.autonavState&&this.j.Nv()):(g.nS(this.player,!0),h6(this));this.yA()};
g.k.hide=function(){e6.prototype.hide.call(this);this.j.Nv();h6(this)};
g.k.yA=function(){var a=this.player.Bk(!0,this.player.isFullscreen());h6(this);d6(this.u);g.bq(this.element,"ytp-autonav-cancelled-small-mode",this.ah(a));g.bq(this.element,"ytp-autonav-cancelled-tiny-mode",this.qG(a));g.bq(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.$m(this.overlay.element,{width:a.width+"px"});if(!this.D)for(a=0;a<this.videos.length;a++)g.bq(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.N("web_player_autonav_empty_suggestions_fix")){var b=g.$M(this.videoData);b&&(this.j.uE(b),this.j!==this.u&&this.u.uE(b))}if(a&&a.length)for(b=0;b<Ugb.length;++b){var c=Ugb[b];if(a&&a[c]){this.videos[b]=new b6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,a6(d,c));g.J(this,this.videos[b]);this.videos[b].Ha(this.K.element)}}this.yA()}};
g.k.EQ=function(a){1===a?(this.J=!1,this.B=this.videoData.clientPlaybackNonce,this.j.rr(),this.Bb&&this.yA()):(this.J=!0,this.Df()&&(2===a?this.j.Vz():3===a&&this.j.Nv()))};
g.k.TZ=function(a){a?this.EQ(1):(this.B=null,this.J=!1)};
g.k.UA=function(){return 1!==this.videoData.autonavState};
g.k.ah=function(a){return(910>a.width||459>a.height)&&!this.qG(a)&&!(400>=a.width||360>=a.height)};
g.k.qG=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Df=function(){return this.Bb&&g.tS(this.player)&&this.UA()&&!this.B};
var Ugb=[1,3,2,4];g.x(i6,g.V);g.k=i6.prototype;g.k.onClick=function(a){this.G.N("web_player_log_click_before_generating_ve_conversion_params")&&this.G.rb(this.element);this.j?this.G.Pa("innertubeCommand",g.Q(this.j.onTap,g.qQ)):g.JS(this.getVideoUrl(),this.G,a);this.G.N("web_player_log_click_before_generating_ve_conversion_params")||this.G.rb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.G.getVideoUrl(a,!1,!1,!0);var b=this.G.W();if(g.OK(b)||g.XK(b)){var c={};b.Ba&&g.OK(b)&&g.TR(c,b.loaderUrl);g.OK(b)&&g.aS(this.G,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.SR(c,b);a=g.jj(a,c)}return a};
g.k.Xa=function(){this.G.Xa(this.element,this.Bb&&this.ea)};
g.k.show=function(){g.V.prototype.show.call(this);this.Xa()};
g.k.hide=function(){g.V.prototype.hide.call(this);this.Xa()};
g.k.hc=function(a){g.V.prototype.hc.call(this,a);this.Xa()};g.x(j6,e6);j6.prototype.show=function(){3!==this.player.getPlayerState()&&(e6.prototype.show.call(this),this.j.Nz(!0),this.j.Zq(!0),this.G.W().nm||this.j.Yq(!0),this.G.Xa(this.element,!0),this.watchButton.hc(!0))};
j6.prototype.hide=function(){e6.prototype.hide.call(this);this.j.Nz(!1);this.j.Zq(!1);this.j.Yq(!1);this.G.Xa(this.element,!1);this.watchButton.hc(!1)};g.x(Pgb,e6);Pgb.prototype.Ra=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.dk;var b=this.subscribeButton;a.subscribed?b.j():b.u()};g.x(k6,g.V);k6.prototype.select=function(){this.api.Nn(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.mB||void 0)&&this.api.rb(this.element)};
k6.prototype.onClick=function(a){if(g.OK(this.api.W())&&this.api.N("web_player_log_click_before_generating_ve_conversion_params")){this.api.rb(this.element);var b=this.suggestion.Ck(),c={};g.tJa(this.api,c,"emb_rel_end");b=g.jj(b,c);g.JS(b,this.api,a)}else g.IS(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
k6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.mP(a)||(this.select(),g.nP(a))}};
k6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.W();this.u=a.wd?!1:b.C};g.x(l6,e6);g.k=l6.prototype;g.k.create=function(){e6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Gp();this.u.T(this.player,"appresize",this.Gp);this.u.T(this.player,"onVideoAreaChange",this.Gp);this.u.T(this.player,"videodatachange",this.onVideoDataChange);this.u.T(this.player,"autonavchange",this.ZI);this.u.T(this.player,"autonavcancel",this.UZ);a=this.videoData.autonavState;a!==this.V&&this.ZI(a);this.u.T(this.element,"transitionend",this.D7)};
g.k.destroy=function(){g.hA(this.u);g.lb(this.stills);this.stills=[];e6.prototype.destroy.call(this);g.$p(this.element,"ytp-show-tiles");this.J.stop();this.V=this.videoData.autonavState};
g.k.UA=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Bb;e6.prototype.show.call(this);g.$p(this.element,"ytp-show-tiles");this.player.W().u?g.Sp(this.J):this.J.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.nS(this.player,!1);m6(this)?(n6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.Vz():3===this.videoData.autonavState&&this.j.Nv()):(g.nS(this.player,!0),n6(this));a!==this.Bb&&this.player.Xa(this.element,!0)};
g.k.hide=function(){var a=this.Bb;e6.prototype.hide.call(this);this.j.Nv();n6(this);a!==this.Bb&&this.player.Xa(this.element,!1)};
g.k.D7=function(a){g.lP(a)===this.element&&this.Gp()};
g.k.Gp=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.$M(d)];if(e.length){g.Yp(this.element,"ytp-endscreen-paginate");var f=this.G.Bk(!0,this.G.isFullscreen());if(a=g.cS(this.G))a=a.Bg()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,t=b/2,u=a<=l-2&&p>=t*n,y=b<=m-2&&p>=q*n;if((q+1)/t*d/h>h/(q/(t+1)*d)&&y)p-=q*n,b+=2;else if(u)p-=t*n,a+=2;else if(y)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.kn(f,n,p);g.$m(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.uE(g.$M(this.videoData));this.j instanceof
c6&&d6(this.j);g.bq(this.element,"ytp-endscreen-takeover",m6(this));n6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,u=0,d&&l>=a-2&&m>=b-2?u=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(u=2):u=2),q=g.pe(q+this.B,c),0!==u){t=this.stills[h];t||(t=new k6(this.player),this.stills[h]=t,f.appendChild(t.element));y=Math.floor(p*m/b);var B=Math.floor(n*l/a),G=Math.floor(p*(m+u)/b)-y-4,M=Math.floor(n*(l+u)/a)-B-4;g.fn(t.element,B,y);g.kn(t.element,M,G);g.$m(t.element,"transitionDelay",
(m+l)/20+"s");g.bq(t.element,"ytp-videowall-still-mini",1===u);g.bq(t.element,"ytp-videowall-still-large",2<u);u=Math.max(M,G);g.bq(t.element,"ytp-videowall-still-round-large",256<=u);g.bq(t.element,"ytp-videowall-still-round-medium",96<u&&256>u);g.bq(t.element,"ytp-videowall-still-round-small",96>=u);q=e[q];t.suggestion!==q&&(t.suggestion=q,u=t.api.W(),y=g.Xp(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",a6(t,q,y),g.OK(u)&&!t.api.N("web_player_log_click_before_generating_ve_conversion_params")&&
(y=q.Ck(),B={},u.Ba&&g.TR(B,u.loaderUrl),g.aS(t.api,"addEmbedsConversionTrackingParams",[B]),y=g.jj(y,g.SR(B,"emb_rel_end")),t.updateValue("url",y)),(q=(q=q.sessionData)&&q.itct)&&t.api.Vf(t.element,q));h++}f.ariaBusy="false";g.bq(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.hf(a.element),g.kb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Gp())};
g.k.VZ=function(){this.B+=this.stills.length;this.Gp()};
g.k.WZ=function(){this.B-=this.stills.length;this.Gp()};
g.k.YU=function(){return this.j.Ik()};
g.k.ZI=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.rr(),this.Bb&&this.Gp()):(this.D=!0,this.Bb&&m6(this)&&(2===a?this.j.Vz():3===a&&this.j.Nv()))};
g.k.UZ=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.Xa(this.stills[a].element,!0);this.ZI(1)}else this.C=null,this.D=!1;this.Gp()};
g.k.Df=function(){return this.Bb&&m6(this)};g.x(o6,e6);o6.prototype.show=function(){if(3!==this.player.getPlayerState()){e6.prototype.show.call(this);var a=this.u;if(a){var b=0<this.j.suggestionData.length;g.bq(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.cS(this.player))||c.LD(!0);this.player.Xa(this.element,!0);this.watchButton.hc(!0)}};
o6.prototype.hide=function(){e6.prototype.hide.call(this);var a;null==(a=g.cS(this.player))||a.LD(!1);this.player.Xa(this.element,!1);this.watchButton.hc(!1)};g.x(Tgb,g.uT);g.k=Tgb.prototype;g.k.hw=function(){var a;if((this.player.W().N("shorts_mode_to_player_api")?this.player.Yb():null==(a=g.cS(this.player))?0:a.Yb())||this.u)return!0;a=this.player.getVideoData();var b;var c=!!((null==a?0:g.$M(a))||(null==a?0:null==(b=a.suggestions)?0:b.length));b=!Qgb(this.player)||c;c=a.dj||g.XK(a.u);var d=this.player.yB();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Df=function(){return this.endScreen.Df()};
g.k.h4=function(){return this.Df()?this.endScreen.YU():!1};
g.k.ra=function(){this.player.Ge("endscreen");g.uT.prototype.ra.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.yb().mf.get("heartbeat"),d=g.$M(a);!d||b.videoId!==d.videoId||a.sY?(this.player.Nn(b.videoId,void 0,void 0,!0,!0,b),c&&c.xG("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.uT.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.uT.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.hw()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Sgb(this);this.C&&Rgb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new g6(this.player):this.endScreen=new l6(this.player),g.J(this,this.endScreen),g.sS(this.player,this.endScreen.element,4))};g.tT("endscreen",Tgb);})(_yt_player);
